language: ruby

sudo: false

before_install:
  - gem install bundler -v 1.14.3
  - bundle --version

script:
  - make test
  - make validate

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - ruby-head
